datasets:
  - name: tinyshakespeare

  - name: pillowbook-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/a0ruo3e2cdoh1dr/pillowbook-ru.zip
    models:
      - name: pillowbook-ru-3-512
        params:
          rnn_size: 256
          num_layers: 3
          num_epochs: 1500
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/3t7wmfk3x02s2qp/pillowbook-ru-3-512.zip
      - name: pillowbook-ru-3-256
        params:
          rnn_size: 256
          num_layers: 3
          num_epochs: 500
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/4rz8kblztlv0zbv/pillowbook-ru-model-3-256.zip

  - name: klim-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/alct8is4cnl9y6h/klim-ru.zip
    models:
      - name: klim-ru-3-512
        params:
          rnn_size: 512
          num_layers: 3
          num_epochs: 150
          save_every: 200
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/w0mwjhvsr8bnk67/klim-ru-model-3-512.zip

  - name: mcdonagh-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/88fohcw5m6zhepe/mcdonagh-ru.zip
    models:
      - name: mcdonagh-ru-3-512
        params:
          rnn_size: 512
          num_layers: 3
          num_epochs: 150
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/ismytgln850j6hk/mcdonagh-ru-3-512.zip
      - name: mcdonagh-ru-3-512-old
        params:
          rnn_size: 512
          num_layers: 3
          num_epochs: 150
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/eflqros14y9gb1o/mcdonagh-ru-3-512-old.zip

  - name: brodsky-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/du0old8mfb4b7bm/brodsky-ru.zip
    models:
      - name: brodsky-ru-3-512
        params:
          rnn_size: 512
          num_layers: 3
          num_epochs: 150
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/swznzugr3mfx5il/brodsky-ru-3-512.zip

  - name: kafka-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/awvv1glcqk8q0wi/kafka-ru.zip
    models:
      - name: kafka-ru-3-512
        params:
          rnn_size: 512
          num_layers: 3
          num_epochs: 150
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/xb1oj76ppa0pmhp/kafka-ru-3-512.zip

  - name: tinyshakespeare-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/ou4t65ytnbjdh2b/tinyshakespeare-ru.zip
    models:
      - name: tinyshakespeare-ru-3-256
        params:
          rnn_size: 512
          num_layers: 3
          num_epochs: 150
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/wj271c0l26v36a6/tinyshakespeare-ru-3-256.zip

  - name: constitution-ukraine-ua
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/qhqxdf9camcz3c6/constitution-ukraine-ua.zip
    models:
      - name: constitution-ukraine-ua

  - name: aeneid-mixed-ua
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/gtnsawv88hy55tx/aeneid-mixed-ua.zip
    models:
      - name: aeneid-mixed-ua-3-512
        params:
          rnn_size: 512
          num_layers: 3
          num_epochs: 150
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/928gfxb4mzvgks7/aeneid-mixed-ua-3-512.zip

  - name: tax-codex-ukraine-ua
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/4egkoglgox8v6jj/tax-codex-ukraine-ua.zip

dirs:
  data: ./data
  models: ./save

server:
  reload_model: 300
  reload_text: 30
  dataset: mcdonagh-ru
  model: mcdonagh-ru-3-512
