datasets:
  - name: tinyshakespeare

  - name: pillowbook-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/a0ruo3e2cdoh1dr/pillowbook-ru.zip
    models:
      - name: pillowbook-ru-3-256
        params:
          rnn_size: 256
          num_layers: 3
          num_epochs: 500
          save_every: 500
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/4rz8kblztlv0zbv/pillowbook-ru-model-3-256.zip

  - name: klim-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/alct8is4cnl9y6h/klim-ru.zip
    models:
      - name: klim-ru-3-512
        params:
          rnn_size: 512
          num_layers: 3
          save_every: 200
        source:
          type: zipfile
          url: https://dl.dropboxusercontent.com/s/w0mwjhvsr8bnk67/klim-ru-model-3-512.zip

  - name: mcdonagh-ru
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/88fohcw5m6zhepe/mcdonagh-ru.zip
    models:
      - name: mcdonagh-ru-3-512
        params:
          rnn_size: 512
          num_layers: 3
          save_every: 200

  - name: constitution-ukraine-ua
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/qhqxdf9camcz3c6/constitution-ukraine-ua.zip
    models:
      - name: constitution-ukraine-ua

  - name: aeneid-mixed-ua
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/gtnsawv88hy55tx/aeneid-mixed-ua.zip
    models:
      - name: aeneid-mixed-ua
        params:
          rnn_size: 512
          num_layers: 3
          save_every: 200

  - name: tax-codex-ukraine-ua
    sources:
      - type: zipfile
        url: https://dl.dropboxusercontent.com/s/4egkoglgox8v6jj/tax-codex-ukraine-ua.zip

dirs:
  data: ./data
  models: ./save

server:
  reload_model: 300
  reload_text: 30
  dataset: klim-ru
  model: klim-ru-3-512
